### ISSUE TITLE
TypeError: Error when calling the metaclass bases     metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by csmobile** [GlobalFishingWatch/pipe-events#1]
This error occurs because one of the dependencies has changed and breaks the configuration.  The solution is to pin the requirements to the versions specified in the attached file.
[require.txt](https://github.com/GlobalFishingWatch/pipe-events/files/1318906/require.txt)

**Comment by andres-arana** [comment]
We have updated the dependencies and pinned them to working versions.
